const invitation = "I’ve been exploring a 24-week Master Key System programme called Unleash Your Power. There’s 7 Days to Change the Way You Use Your Mind if you want to try it for yourself. No pressure — I just thought you might find it interesting.";
const startFreeUrl = "https://unleashyourpowerwithtariq.com/start-free/";

export function referralPage(data) {
  return {
    route: data.routes.referral,
    language: "en",
    title: "Share the Journey | Unleash Your Power",
    description: "Invite someone you care about to begin 7 Days to Change the Way You Use Your Mind with Unleash Your Power.",
    titleKey: "route.referral.metaTitle",
    descriptionKey: "route.referral.metaDescription",
    body: `<main class="referralPage" id="main-content">
      <section class="referralHero" aria-labelledby="referral-title">
        <div class="referralHero__copy"><p class="eyebrow">SHARE THE JOURNEY</p><h1 id="referral-title">Become an Unleash Your Power Affiliate</h1><p class="referralHero__lead">Help Someone You Care About <em>Begin Their Journey</em></p><p>If the Master Key System has helped you think more clearly, feel more focused, and create with greater confidence, you may know someone who could benefit from experiencing it too.</p><p>Introduce them to 7 Days to Change the Way You Use Your Mind.<br>No pressure. Just a meaningful opportunity.</p><a class="button--primary" href="#share-personally">REFER A FRIEND</a><small class="referralTrust">🔒 Secure. Private. No spam.</small></div>
        <figure class="referralHero__portrait"><img src="/images/tariq-happiness-harmony.png" width="1088" height="1445" loading="eager" fetchpriority="high" alt="Tariq Saddique, guide for the Unleash Your Power journey."></figure>
      </section>
      <section class="referralSection" aria-labelledby="how-it-works"><p class="eyebrow">A SIMPLE INVITATION</p><h2 id="how-it-works">HOW IT WORKS</h2><div class="referralCards"><article><span aria-hidden="true">01</span><h3>Think of someone</h3><p>Think of a friend, family member or colleague who may benefit from more clarity, confidence and direction.</p></article><article><span aria-hidden="true">02</span><h3>Introduce them</h3><p>Share your unique referral link or invite them directly. It only takes a moment.</p></article><article><span aria-hidden="true">03</span><h3>Let them start</h3><p>They’ll get immediate access to 7 Days to Change the Way You Use Your Mind.</p></article></div></section>
      <section class="referralSection affiliateLinkSection" aria-labelledby="affiliate-link-title"><p class="eyebrow">YOUR PERSONAL AFFILIATE LINK</p><h2 id="affiliate-link-title">Share your link wherever you connect.</h2><p>Use your unique link on your website, social media, email, or in a community you serve. It takes people directly to 7 Days to Change the Way You Use Your Mind.</p><div class="affiliateLinkBuilder"><label for="affiliate-code">Your affiliate code</label><div><input id="affiliate-code" data-affiliate-code maxlength="40" inputmode="text" placeholder="yourname"><button type="button" class="button--secondary" data-affiliate-build>CREATE LINK</button></div><span class="affiliateLinkBuilder__label">Your affiliate link</span><a data-affiliate-link href="https://unleashyourpowerwithtariq.com/start-free/">https://unleashyourpowerwithtariq.com/start-free/</a><div class="affiliateLinkBuilder__actions"><button type="button" class="button--secondary" data-affiliate-copy-link>Copy Link</button><button type="button" class="button--secondary" data-affiliate-open-link>Open Link</button></div><p data-affiliate-link-status role="status" aria-live="polite"></p><small>Use this link on your website, social media, WhatsApp, email or community page.</small></div><div class="affiliateJourney" aria-label="Referral journey"><span>Share</span><b aria-hidden="true">→</b><span>Start your 7 days</span><b aria-hidden="true">→</b><span>Begin change</span></div></section>
      <section class="referralSection affiliateReward" aria-labelledby="affiliate-reward-title"><p class="eyebrow">YOUR AFFILIATE REWARD</p><h2 id="affiliate-reward-title">Earn 5% for every complete-course referral</h2><p>Share your personal affiliate link. When someone you refer purchases the full Unleash Your Power programme, you earn 5% of the completed sale value.</p><dl class="affiliateReward__example"><div><dt>Full programme</dt><dd>£997</dd></div><div><dt>Affiliate reward</dt><dd>5%</dd></div><div class="affiliateReward__total"><dt>You earn</dt><dd>£49.85</dd></div></dl><p class="affiliateReward__eligibility">Rewards apply to eligible, completed, non-refunded purchases attributed to your tracked affiliate link. Payment terms and eligibility are subject to the affiliate terms.</p></section>
      <section class="referralSection referralWhy" aria-labelledby="why-refer"><p class="eyebrow">SHARING WITH PURPOSE</p><h2 id="why-refer">WHY REFER?</h2><div class="referralReasons"><p><span aria-hidden="true">✦</span>Meaningful rewards for helping others</p><p><span aria-hidden="true">✦</span>No selling. No pressure.</p><p><span aria-hidden="true">✦</span>Just sharing an opportunity that helped you</p><p><span aria-hidden="true">✦</span>You could be the beginning of something life-changing</p></div></section>
      <section class="referralInvite" id="personal-invite" aria-labelledby="invite-title"><p class="eyebrow">YOUR PERSONAL INVITE</p><h2 id="invite-title">Share a thoughtful first step.</h2><blockquote data-referral-copy>${invitation}</blockquote><div class="referralInvite__actions"><a class="button--primary" data-referral-whatsapp href="https://wa.me/?text=${encodeURIComponent(`${invitation} ${startFreeUrl}`)}" target="_blank" rel="noopener noreferrer">SHARE ON WHATSAPP</a><button class="button--secondary" data-referral-copy-button type="button">COPY MESSAGE</button></div><p class="referralInvite__status" data-referral-status role="status" aria-live="polite"></p><p class="referralInvite__url">${startFreeUrl}</p></section>
      <section class="referralSection affiliateTerms" aria-labelledby="affiliate-terms-title"><p class="eyebrow">AFFILIATE TERMS SUMMARY</p><h2 id="affiliate-terms-title">Clear terms for sharing responsibly.</h2><ul><li>Affiliates earn 5% of eligible completed full-course sales. The current full-course price is £997; the current example reward is £49.85.</li><li>Commission applies only to purchases successfully attributed to the affiliate’s tracked link or code.</li><li>Refunded, cancelled, reversed or fraudulent transactions are not commissionable. Self-referrals are not eligible unless explicitly approved.</li><li>Affiliate codes and links must not be altered to misrepresent attribution. Affiliates must not make misleading claims about the programme or guaranteed outcomes.</li><li>Affiliates are responsible for complying with applicable disclosure rules when promoting affiliate links.</li><li>Payment timing and method will be confirmed as part of the approved affiliate arrangement. Unleash Your Power may review or reject affiliate applications where appropriate.</li><li>Programme prices and affiliate terms may change in future, but accrued eligible commissions should not be retrospectively reduced.</li></ul></section>
      <section class="referralSection affiliateApplication" aria-labelledby="affiliate-application-title"><p class="eyebrow">JOIN THE COMMUNITY</p><h2 id="affiliate-application-title">Apply to become an affiliate.</h2><p>Tell us a little about how you would share the experience. Approved affiliates earn 5% on eligible completed purchases of the full programme.</p><form data-affiliate-application><div class="affiliateApplication__grid"><label>First Name<input name="firstName" required></label><label>Surname<input name="surname" required></label><label>Email<input type="email" name="email" required></label><label>WhatsApp<input name="whatsapp" inputmode="tel"></label><label>Website / Social Media / Community URL<input name="platform"></label><label>Organisation or Group Name<input name="organisation"></label></div><label>How do you plan to promote Unleash Your Power?<textarea name="plan" rows="4" required></textarea></label><label class="affiliateConsent"><input type="checkbox" name="terms" required> I agree to the affiliate terms and understand that affiliate approval is required before commission eligibility.</label><button class="button--primary" type="submit">SUBMIT AFFILIATE APPLICATION</button><p data-affiliate-application-status role="status" aria-live="polite"></p></form></section>
      <section class="referralSection affiliateToolkit" aria-labelledby="affiliate-toolkit-title"><p class="eyebrow">READY-TO-SHARE RESOURCES</p><h2 id="affiliate-toolkit-title">Affiliate Toolkit</h2><p>Use these approved resources when introducing someone to the programme:</p><ul><li>7 Days to Change the Way You Use Your Mind link</li><li>Personal invitation message</li><li>Master Key System study page</li></ul></section>
      <section class="referralCta"><div><p class="eyebrow">PASS IT ON</p><h2>Ready to share the gift of growth?</h2><p>Your invitation could be the key that unlocks their next chapter.</p></div><a class="button--primary" href="#personal-invite">REFER A FRIEND TODAY</a></section>
    </main>`,
    scripts: ["/assets/referral.mjs"],
  };
}

export { invitation, startFreeUrl };
