const invitation = "I’ve been exploring a 24-week Master Key System programme called Unleash Your Power. There’s a free 7-Day Experience if you want to try it for yourself. No pressure — I just thought you might find it interesting.";
const startFreeUrl = "https://toslondon9-maker.github.io/start-free/";

export function referralPage(data) {
  return {
    route: data.routes.referral,
    language: "en",
    title: "Share the Journey | Unleash Your Power",
    description: "Invite someone you care about to begin the free Unleash Your Power 7-Day Experience.",
    titleKey: "route.referral.metaTitle",
    descriptionKey: "route.referral.metaDescription",
    body: `<main class="referralPage" id="main-content">
      <section class="referralHero" aria-labelledby="referral-title">
        <div class="referralHero__copy"><p class="eyebrow">SHARE THE JOURNEY</p><h1 id="referral-title">Become an Unleash Your Power Affiliate</h1><p class="referralHero__lead">Help Someone You Care About <em>Begin Their Journey</em></p><p>If the Master Key System has helped you think more clearly, feel more focused, and create with greater confidence, you may know someone who could benefit from experiencing it too.</p><p>Introduce them to the 7-Day Experience.<br>No pressure. Just a meaningful opportunity.</p><a class="button--primary" href="#personal-invite">REFER A FRIEND</a><small class="referralTrust">🔒 Secure. Private. No spam.</small></div>
        <figure class="referralHero__portrait"><img src="/images/tariq-happiness-harmony.png" width="1088" height="1445" loading="eager" fetchpriority="high" alt="Tariq Saddique, guide for the Unleash Your Power journey."></figure>
      </section>
      <section class="referralSection" aria-labelledby="how-it-works"><p class="eyebrow">A SIMPLE INVITATION</p><h2 id="how-it-works">HOW IT WORKS</h2><div class="referralCards"><article><span aria-hidden="true">01</span><h3>Think of someone</h3><p>Think of a friend, family member or colleague who may benefit from more clarity, confidence and direction.</p></article><article><span aria-hidden="true">02</span><h3>Introduce them</h3><p>Share your unique referral link or invite them directly. It only takes a moment.</p></article><article><span aria-hidden="true">03</span><h3>Let them start free</h3><p>They’ll get immediate access to the 7-Day Experience completely free.</p></article></div></section>
      <section class="referralSection affiliateLinkSection" aria-labelledby="affiliate-link-title"><p class="eyebrow">YOUR PERSONAL AFFILIATE LINK</p><h2 id="affiliate-link-title">Share your link wherever you connect.</h2><p>Use your unique link on your website, social media, email, or in a community you serve. It takes people directly to the free 7-Day Experience.</p><div class="affiliateLinkBuilder"><label for="affiliate-code">Your affiliate code</label><div><input id="affiliate-code" data-affiliate-code maxlength="40" inputmode="text" placeholder="yourname"><button type="button" class="button--secondary" data-affiliate-build>CREATE LINK</button></div><a data-affiliate-link href="https://toslondon9-maker.github.io/start-free/">https://toslondon9-maker.github.io/start-free/</a></div><div class="affiliateJourney" aria-label="Referral journey"><span>Share</span><b aria-hidden="true">→</b><span>Start free</span><b aria-hidden="true">→</b><span>Begin change</span></div></section>
      <section class="referralSection referralWhy" aria-labelledby="why-refer"><p class="eyebrow">SHARING WITH PURPOSE</p><h2 id="why-refer">WHY REFER?</h2><div class="referralReasons"><p><span aria-hidden="true">✦</span>Meaningful rewards for helping others</p><p><span aria-hidden="true">✦</span>No selling. No pressure.</p><p><span aria-hidden="true">✦</span>Just sharing an opportunity that helped you</p><p><span aria-hidden="true">✦</span>You could be the beginning of something life-changing</p></div></section>
      <section class="referralInvite" id="personal-invite" aria-labelledby="invite-title"><p class="eyebrow">YOUR PERSONAL INVITE</p><h2 id="invite-title">Share a thoughtful first step.</h2><blockquote data-referral-copy>${invitation}</blockquote><div class="referralInvite__actions"><a class="button--primary" data-referral-whatsapp href="https://wa.me/?text=${encodeURIComponent(`${invitation} ${startFreeUrl}`)}" target="_blank" rel="noopener noreferrer">SHARE ON WHATSAPP</a><button class="button--secondary" data-referral-copy-button type="button">COPY MESSAGE</button></div><p class="referralInvite__status" data-referral-status role="status" aria-live="polite"></p><p class="referralInvite__url">${startFreeUrl}</p></section>
      <section class="referralSection affiliateApplication" aria-labelledby="affiliate-application-title"><p class="eyebrow">JOIN THE COMMUNITY</p><h2 id="affiliate-application-title">Apply to become an affiliate.</h2><p>Tell us a little about how you would share the experience. Affiliate terms and approval will be confirmed personally.</p><form data-affiliate-application><div class="affiliateApplication__grid"><label>First Name<input name="firstName" required></label><label>Surname<input name="surname" required></label><label>Email<input type="email" name="email" required></label><label>WhatsApp<input name="whatsapp" inputmode="tel"></label><label>Website / Social Media / Community URL<input name="platform"></label><label>Organisation or Group Name<input name="organisation"></label></div><label>How do you plan to promote Unleash Your Power?<textarea name="plan" rows="4" required></textarea></label><label class="affiliateConsent"><input type="checkbox" name="terms" required> I agree to the affiliate terms and understand that affiliate approval is required before commission eligibility.</label><button class="button--primary" type="submit">SUBMIT AFFILIATE APPLICATION</button><p data-affiliate-application-status role="status" aria-live="polite"></p></form></section>
      <section class="referralSection affiliateToolkit" aria-labelledby="affiliate-toolkit-title"><p class="eyebrow">READY-TO-SHARE RESOURCES</p><h2 id="affiliate-toolkit-title">Affiliate Toolkit</h2><p>Use these approved resources when introducing someone to the programme:</p><ul><li>Free 7-Day Experience link</li><li>Personal invitation message</li><li>Master Key System study page</li></ul></section>
      <section class="referralCta"><div><p class="eyebrow">PASS IT ON</p><h2>Ready to share the gift of growth?</h2><p>Your invitation could be the key that unlocks their next chapter.</p></div><a class="button--primary" href="#personal-invite">REFER A FRIEND TODAY</a></section>
    </main>`,
    scripts: ["/assets/referral.mjs"],
  };
}

export { invitation, startFreeUrl };
