$ErrorActionPreference = 'Stop'

$siteRoot = Split-Path -Parent $PSScriptRoot
$htmlPath = Join-Path $siteRoot 'index.html'
$rscPath = Join-Path $siteRoot 'index.rsc'
$cssPath = Join-Path $siteRoot 'assets/index-Bgwsdhov.css'

$heroHtml = @'
<section class="hero haanelHero" id="top"><div class="orb orbOne"></div><div class="orb orbTwo"></div><div class="heroCopy"><p class="eyebrow">CHARLES F. HAANEL’S MASTER KEY SYSTEM · GUIDED BY TARIQ SADDIQUE</p><h1><span>Charles F. Haanel revealed the Master Key.</span><em>Tariq helps you use it.</em></h1><p class="lead">Discover the progressive 24-part system that has challenged students for more than a century—then experience how focused coaching turns its principles into disciplined daily action.</p><div class="actions"><a class="primary" href="#free-taster">Try the free 7-day taster <span>→</span></a><a class="secondary" href="#meet-tariq">Meet Tariq, your guide</a></div><div class="trust"><span>◇ The original 24-part system</span><span>◉ Live coaching on Zoom</span><span>◎ English worldwide</span></div></div><div class="heroVisual dualPortraits"><figure class="authorityPortrait haanelAuthority"><img src="/images/master-key-wisdom.png" alt="Charles F. Haanel, author of The Master Key System"/><figcaption><span>THE ORIGINAL SYSTEM</span><strong>Charles F. Haanel</strong><small>Author · Businessman · 1866–1949</small></figcaption></figure><figure class="authorityPortrait tariqAuthority"><img src="/images/tariq-happiness-harmony.png" alt="Tariq Saddique, Master Key System coach"/><figcaption><span>YOUR MODERN GUIDE</span><strong>Tariq Saddique</strong><small>Coach · Mentor · Accountability partner</small></figcaption></figure></div></section>
'@

$progressionHtml = @'
<section class="weeklyProgression section" id="weekly-progression"><div class="sectionIntro centered"><p class="eyebrow">THE TRANSFORMATION IS IN THE PROGRESSION</p><h2>The power unfolds week by week.</h2><p>Each weekly lesson builds upon the last—deepening your awareness, strengthening your concentration and turning powerful ideas into lived practice.</p></div><div class="progressionGrid"><article><span>01</span><h3>Notice</h3><p>Become aware of the thoughts, reactions and repeated patterns that normally operate unnoticed.</p></article><article><span>02</span><h3>Practise</h3><p>Train attention through a deliberate daily exercise, building on the mental faculty developed the week before.</p></article><article><span>03</span><h3>Become</h3><p>Turn repeated practice into calmer choices, stronger self-trust and purposeful action in everyday life.</p></article></div><blockquote>As you move deeper into <em>The Master Key System</em>, an almost magical process can begin to unfold: you notice more, respond differently and act with greater intention.</blockquote><p class="progressionNote">It can feel magical, but it is not instant magic. The change comes from disciplined study, progressive practice and your willingness to apply each lesson.</p></section><section class="meetTariq section" id="meet-tariq"><figure><img src="/images/tariq-happiness-harmony.png" alt="Tariq Saddique, your Master Key System guide" loading="lazy"/></figure><div><p class="eyebrow">FROM TIMELESS KNOWLEDGE TO LIVED EXPERIENCE</p><h2>Haanel created the system. Tariq helps you live it.</h2><p>The book gives you the principles. My coaching gives you the structure, explanation and accountability to keep moving when the work becomes deeper—and when old habits try to pull you back.</p><div class="coachValue"><span>Clear weekly teaching</span><span>Guided mental exercises</span><span>Honest accountability</span><span>Practical application</span></div><p>I will help you study each lesson in sequence, understand what it asks of you and connect the inner work to the goals, decisions and relationships that matter in your life.</p><div class="actions"><a class="primary" href="#free-taster">Experience my coaching free →</a><a class="secondary" href="mailto:toslondon9@gmail.com?subject=Master%20Key%20Discovery%20Call&amp;body=Hello%20Tariq%2C%0A%0AI%27d%20like%20to%20learn%20more%20about%20your%20Master%20Key%20coaching.%0A%0AMy%20main%20goal%20is%3A%20">Ask Tariq a question</a></div></div></section>
'@

$heroRsc = @'
["$","section",null,{"className":"hero haanelHero","id":"top","children":[["$","div",null,{"className":"orb orbOne"}],["$","div",null,{"className":"orb orbTwo"}],["$","div",null,{"className":"heroCopy","children":[["$","p",null,{"className":"eyebrow","children":"CHARLES F. HAANEL’S MASTER KEY SYSTEM · GUIDED BY TARIQ SADDIQUE"}],["$","h1",null,{"children":[["$","span",null,{"children":"Charles F. Haanel revealed the Master Key."}],["$","em",null,{"children":"Tariq helps you use it."}]]}],["$","p",null,{"className":"lead","children":"Discover the progressive 24-part system that has challenged students for more than a century—then experience how focused coaching turns its principles into disciplined daily action."}],["$","div",null,{"className":"actions","children":[["$","a",null,{"className":"primary","href":"#free-taster","children":["Try the free 7-day taster ",["$","span",null,{"children":"→"}]]}],["$","a",null,{"className":"secondary","href":"#meet-tariq","children":"Meet Tariq, your guide"}]]}],["$","div",null,{"className":"trust","children":[["$","span",null,{"children":"◇ The original 24-part system"}],["$","span",null,{"children":"◉ Live coaching on Zoom"}],["$","span",null,{"children":"◎ English worldwide"}]]}]]}],["$","div",null,{"className":"heroVisual dualPortraits","children":[["$","figure",null,{"className":"authorityPortrait haanelAuthority","children":[["$","img",null,{"src":"/images/master-key-wisdom.png","alt":"Charles F. Haanel, author of The Master Key System"}],["$","figcaption",null,{"children":[["$","span",null,{"children":"THE ORIGINAL SYSTEM"}],["$","strong",null,{"children":"Charles F. Haanel"}],["$","small",null,{"children":"Author · Businessman · 1866–1949"}]]}]]}],["$","figure",null,{"className":"authorityPortrait tariqAuthority","children":[["$","img",null,{"src":"/images/tariq-happiness-harmony.png","alt":"Tariq Saddique, Master Key System coach"}],["$","figcaption",null,{"children":[["$","span",null,{"children":"YOUR MODERN GUIDE"}],["$","strong",null,{"children":"Tariq Saddique"}],["$","small",null,{"children":"Coach · Mentor · Accountability partner"}]]}]]}]]}]]}]
'@.Trim()

$progressionRsc = @'
["$","section",null,{"className":"weeklyProgression section","id":"weekly-progression","children":[["$","div",null,{"className":"sectionIntro centered","children":[["$","p",null,{"className":"eyebrow","children":"THE TRANSFORMATION IS IN THE PROGRESSION"}],["$","h2",null,{"children":"The power unfolds week by week."}],["$","p",null,{"children":"Each weekly lesson builds upon the last—deepening your awareness, strengthening your concentration and turning powerful ideas into lived practice."}]]}],["$","div",null,{"className":"progressionGrid","children":[["$","article",null,{"children":[["$","span",null,{"children":"01"}],["$","h3",null,{"children":"Notice"}],["$","p",null,{"children":"Become aware of the thoughts, reactions and repeated patterns that normally operate unnoticed."}]]}],["$","article",null,{"children":[["$","span",null,{"children":"02"}],["$","h3",null,{"children":"Practise"}],["$","p",null,{"children":"Train attention through a deliberate daily exercise, building on the mental faculty developed the week before."}]]}],["$","article",null,{"children":[["$","span",null,{"children":"03"}],["$","h3",null,{"children":"Become"}],["$","p",null,{"children":"Turn repeated practice into calmer choices, stronger self-trust and purposeful action in everyday life."}]]}]]}],["$","blockquote",null,{"children":["As you move deeper into ",["$","em",null,{"children":"The Master Key System"}],", an almost magical process can begin to unfold: you notice more, respond differently and act with greater intention."]}],["$","p",null,{"className":"progressionNote","children":"It can feel magical, but it is not instant magic. The change comes from disciplined study, progressive practice and your willingness to apply each lesson."}]]}],
["$","section",null,{"className":"meetTariq section","id":"meet-tariq","children":[["$","figure",null,{"children":["$","img",null,{"src":"/images/tariq-happiness-harmony.png","alt":"Tariq Saddique, your Master Key System guide","loading":"lazy"}]}],["$","div",null,{"children":[["$","p",null,{"className":"eyebrow","children":"FROM TIMELESS KNOWLEDGE TO LIVED EXPERIENCE"}],["$","h2",null,{"children":"Haanel created the system. Tariq helps you live it."}],["$","p",null,{"children":"The book gives you the principles. My coaching gives you the structure, explanation and accountability to keep moving when the work becomes deeper—and when old habits try to pull you back."}],["$","div",null,{"className":"coachValue","children":[["$","span",null,{"children":"Clear weekly teaching"}],["$","span",null,{"children":"Guided mental exercises"}],["$","span",null,{"children":"Honest accountability"}],["$","span",null,{"children":"Practical application"}]]}],["$","p",null,{"children":"I will help you study each lesson in sequence, understand what it asks of you and connect the inner work to the goals, decisions and relationships that matter in your life."}],["$","div",null,{"className":"actions","children":[["$","a",null,{"className":"primary","href":"#free-taster","children":"Experience my coaching free →"}],["$","a",null,{"className":"secondary","href":"mailto:toslondon9@gmail.com?subject=Master%20Key%20Discovery%20Call&body=Hello%20Tariq%2C%0A%0AI%27d%20like%20to%20learn%20more%20about%20your%20Master%20Key%20coaching.%0A%0AMy%20main%20goal%20is%3A%20","children":"Ask Tariq a question"}]]}]]}]]}]
'@.Trim().Replace("`r", '').Replace("`n", '')

$css = @'

/* Haanel-first conversion story */
.haanelHero{grid-template-columns:minmax(360px,1fr) minmax(420px,1.08fr);min-height:calc(100vh - 80px)}.haanelHero .heroCopy{max-width:760px}.haanelHero h1{display:grid;gap:.35rem;font-size:clamp(3rem,5.6vw,6.6rem);line-height:.92}.haanelHero h1 span{display:block}.haanelHero h1 em{display:block;font-size:.72em;line-height:1.02}.dualPortraits{display:grid;grid-template-columns:1fr 1fr;gap:1rem;align-items:end}.authorityPortrait{position:relative;margin:0;background:#071525;border:1px solid rgba(190,139,61,.55);box-shadow:0 25px 70px rgba(14,24,34,.22);overflow:hidden}.authorityPortrait img{display:block;width:100%;aspect-ratio:4/5;object-fit:cover}.haanelAuthority img{object-position:5% 50%;filter:sepia(.18) contrast(1.04)}.tariqAuthority{transform:translateY(2rem)}.authorityPortrait figcaption{display:grid;gap:.15rem;padding:1rem 1.1rem;background:#071525;color:#fff}.authorityPortrait figcaption span{font-size:.65rem;letter-spacing:.17em;color:#d2a858}.authorityPortrait figcaption strong{font-family:Georgia,serif;font-size:1.1rem}.authorityPortrait figcaption small{font-size:.7rem;color:#aeb8c2}.weeklyProgression{background:#f5f0e7}.progressionGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1.2rem;margin:2.5rem 0}.progressionGrid article{padding:2rem;background:#fff;border-top:3px solid #b68032;box-shadow:0 16px 40px rgba(31,42,52,.08)}.progressionGrid span{font-family:Georgia,serif;font-size:2.4rem;color:#c99b58}.progressionGrid h3{font-family:Georgia,serif;font-size:1.7rem;margin:.55rem 0}.progressionGrid p{color:#596570;line-height:1.7}.weeklyProgression blockquote{max-width:980px;margin:2.8rem auto 1rem;padding:2rem clamp(1.5rem,4vw,4rem);font-family:Georgia,serif;font-size:clamp(1.5rem,2.6vw,2.5rem);line-height:1.35;text-align:center;color:#102235;border-left:0}.progressionNote{max-width:760px;margin:0 auto;text-align:center;color:#68737d;line-height:1.7}.meetTariq{display:grid;grid-template-columns:minmax(280px,.78fr) minmax(360px,1.22fr);gap:clamp(2.5rem,6vw,6rem);align-items:center}.meetTariq figure{margin:0}.meetTariq figure img{display:block;width:100%;max-height:720px;object-fit:cover;object-position:center top;box-shadow:0 24px 60px rgba(16,29,42,.18)}.meetTariq h2{font-size:clamp(2.4rem,4.5vw,4.8rem);margin:.45rem 0 1.2rem}.meetTariq>div>p{color:#56616b;line-height:1.75}.coachValue{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin:1.5rem 0}.coachValue span{padding:.8rem 1rem;background:#f3eee5;border-left:3px solid #b68032;color:#17283a;font-weight:700}
@media(max-width:1080px){.haanelHero{grid-template-columns:1fr}.dualPortraits{max-width:760px;margin:0 auto}.tariqAuthority{transform:none}}
@media(max-width:760px){.dualPortraits{grid-template-columns:1fr 1fr;gap:.55rem}.authorityPortrait figcaption{padding:.75rem}.authorityPortrait figcaption small{display:none}.progressionGrid{grid-template-columns:1fr}.meetTariq{grid-template-columns:1fr}.meetTariq figure{max-width:520px;margin:0 auto}.coachValue{grid-template-columns:1fr}.haanelHero h1{font-size:clamp(2.8rem,13vw,4.5rem)}}
'@

$html = Get-Content -Raw -LiteralPath $htmlPath
$rsc = Get-Content -Raw -LiteralPath $rscPath
$rscLines = $rsc -split "`r?`n"
$oldMetaLine = $rscLines | Where-Object { $_.StartsWith('0:') } | Select-Object -First 1
$oldMainLine = $rscLines | Where-Object { $_.StartsWith('1:') } | Select-Object -First 1
if (-not $oldMetaLine -or -not $oldMainLine) { throw 'Homepage RSC payload lines were not found.' }
if (-not $html.Contains('<section class="hero" id="top">')) { throw 'Existing hero was not found.' }
if (-not $html.Contains('<section class="taster section" id="free-taster">')) { throw 'Taster insertion point was not found.' }

$heroPatternHtml = '<section class="hero" id="top">.*?</section><section class="principle">'
$heroHtmlRegex = [regex]::new($heroPatternHtml)
$html = $heroHtmlRegex.Replace($html, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $heroHtml + '<section class="principle">' }, 1)
$html = $html.Replace('<section class="taster section" id="free-taster">', $progressionHtml + '<section class="taster section" id="free-taster">')
$html = $html.Replace('<a href="#about-system">The System</a>', '<a href="#about-system">Charles F. Haanel</a>')

$newTitle = "Charles F. Haanel’s Master Key System | Coaching with Tariq Saddique"
$newDescription = "Discover Charles F. Haanel’s progressive 24-part Master Key System with practical coaching, weekly guidance and accountability from Tariq Saddique."
$newSocialTitle = "Charles F. Haanel’s Master Key System with Tariq Saddique"
$html = $html.Replace('<title>Unleash Your Power | 24-Week Master Key Coaching</title>', '<title>' + $newTitle + '</title>')
$html = $html.Replace('<meta name="description" content="A guided 24-week journey with Tariq Saddique through clarity, visualisation, concentration, contemplation and practical inner mastery."/>', '<meta name="description" content="' + $newDescription + '"/>')
$html = $html.Replace('<meta property="og:title" content="Unleash Your Power with Tariq Saddique"/>', '<meta property="og:title" content="' + $newSocialTitle + '"/>')
$html = $html.Replace('<meta property="og:description" content="A guided 24-week Master Key journey through clarity, visualisation, concentration, contemplation and practical action."/>', '<meta property="og:description" content="A progressive 24-part system brought to life through weekly coaching, deliberate practice and accountability."/>')
$html = $html.Replace('<meta name="twitter:title" content="Unleash Your Power with Tariq Saddique"/>', '<meta name="twitter:title" content="' + $newSocialTitle + '"/>')
$html = $html.Replace('<meta name="twitter:description" content="A structured 24-week Master Key coaching journey for practical inner mastery."/>', '<meta name="twitter:description" content="Discover the progressive weekly process behind The Master Key System and experience it with practical coaching."/>')

$heroPatternRsc = '\["\$","section",null,\{"className":"hero","id":"top".*?(?=,\["\$","section",null,\{"className":"principle")'
$heroRegex = [regex]::new($heroPatternRsc)
$newMainLine = $heroRegex.Replace($oldMainLine, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $heroRsc }, 1)
$newMainLine = $newMainLine.Replace('["$","section",null,{"className":"taster section","id":"free-taster"', $progressionRsc + ',["$","section",null,{"className":"taster section","id":"free-taster"')
$newMainLine = $newMainLine.Replace('"children":"The System"', '"children":"Charles F. Haanel"')

$newMetaLine = $oldMetaLine.Replace('Unleash Your Power | 24-Week Master Key Coaching', $newTitle)
$newMetaLine = $newMetaLine.Replace('A guided 24-week journey with Tariq Saddique through clarity, visualisation, concentration, contemplation and practical inner mastery.', $newDescription)
$newMetaLine = $newMetaLine.Replace('Unleash Your Power with Tariq Saddique', $newSocialTitle)
$newMetaLine = $newMetaLine.Replace('A guided 24-week Master Key journey through clarity, visualisation, concentration, contemplation and practical action.', 'A progressive 24-part system brought to life through weekly coaching, deliberate practice and accountability.')
$newMetaLine = $newMetaLine.Replace('A structured 24-week Master Key coaching journey for practical inner mastery.', 'Discover the progressive weekly process behind The Master Key System and experience it with practical coaching.')

if ($newMainLine -eq $oldMainLine) { throw 'RSC hero transformation did not apply.' }

$rsc = $rsc.Replace($oldMetaLine, $newMetaLine).Replace($oldMainLine, $newMainLine)

function Escape-RscLine([string]$line) {
  return $line.Replace('\', '\\').Replace('"', '\"').Replace('&', '\u0026').Replace('<', '\u003c').Replace('>', '\u003e') + '\n'
}

$oldMetaEscaped = Escape-RscLine $oldMetaLine
$newMetaEscaped = Escape-RscLine $newMetaLine
$oldMainEscaped = Escape-RscLine $oldMainLine
$newMainEscaped = Escape-RscLine $newMainLine
if (-not $html.Contains($oldMetaEscaped)) { throw 'Embedded metadata payload was not found.' }
if (-not $html.Contains($oldMainEscaped)) { throw 'Embedded homepage payload was not found.' }
$html = $html.Replace($oldMetaEscaped, $newMetaEscaped).Replace($oldMainEscaped, $newMainEscaped)

$existingCss = Get-Content -Raw -LiteralPath $cssPath
if ($existingCss.Contains('/* Haanel-first conversion story */')) { throw 'Haanel-first styles have already been added.' }

Set-Content -LiteralPath $htmlPath -Value $html -NoNewline
Set-Content -LiteralPath $rscPath -Value $rsc -NoNewline
Add-Content -LiteralPath $cssPath -Value $css -NoNewline
