import { haanelQuotes, haanelTopics } from "../content/haanel-quotes.mjs";
import { t } from "../content/translations.mjs";

const esc = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const labels = (language) => Object.fromEntries(haanelTopics.map((topic) => [topic, t(`resources.quotes.topic.${topic}`, language)]));

function card(item, language, topicLabels) {
  const topics = item.topics.join(" ");
  return `<article class="resourcesQuotes__card" data-haanel-quote="${esc(item.id)}" data-quote-topics="${esc(topics)}"><blockquote>${esc(item.quote)}</blockquote><p class="resourcesQuotes__reflection"><span data-i18n="resources.quotes.reflectionLabel">${esc(t("resources.quotes.reflectionLabel", language))}</span> ${esc(item.reflection)}</p><p class="resourcesQuotes__source">${esc(item.source)} · ${esc(item.part)} · ${esc(item.lesson)}</p><div class="resourcesQuotes__cardMeta"><span>${item.topics.map((topic) => `<span class="resourcesQuotes__tag">${esc(topicLabels[topic])}</span>`).join(" ")}</span><a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener noreferrer" data-i18n="resources.quotes.sourceLink">${esc(t("resources.quotes.sourceLink", language))}</a></div></article>`;
}

export function renderHaanelQuoteExperience(data, language) {
  const topicLabels = labels(language);
  const featured = haanelQuotes[0];
  const filters = ["all", ...haanelTopics].map((topic) => `<button type="button" class="resourcesQuotes__filter" data-quote-filter="${topic}" aria-pressed="${topic === "all" ? "true" : "false"}">${esc(topic === "all" ? t("resources.quotes.all", language) : topicLabels[topic])}</button>`).join("");
  const cards = haanelQuotes.map((item) => card(item, language, topicLabels)).join("");
  return `<section class="resourcesQuoteExperience" id="haanel-wisdom" aria-labelledby="haanel-wisdom-title"><div class="resourcesQuotes__feature"><p class="eyebrow" data-i18n="resources.quotes.eyebrow">${esc(t("resources.quotes.eyebrow", language))}</p><h2 id="haanel-wisdom-title" data-i18n="resources.quotes.title">${esc(t("resources.quotes.title", language))}</h2><blockquote>${esc(featured.quote)}</blockquote><p class="resourcesQuotes__source">${esc(featured.source)} · ${esc(featured.part)} · ${esc(featured.lesson)}</p><div class="resourcesQuotes__featureActions"><a class="resourcesQuotes__featuredLink button button--secondary" href="${esc(data.routes.masterKeySystem)}" data-i18n="resources.quotes.featuredLink">${esc(t("resources.quotes.featuredLink", language))}</a><a class="resourcesQuotes__sourceFile button button--secondary" href="/downloads/2026-master-key-system.pdf" data-i18n="resources.quotes.sourceFile">${esc(t("resources.quotes.sourceFile", language))}</a></div></div><p class="resourcesQuotes__originalNote" data-i18n="resources.quotes.originalNote">${esc(t("resources.quotes.originalNote", language))}</p><div class="resourcesQuotes__random"><div><p class="eyebrow" data-i18n="resources.quotes.randomEyebrow">${esc(t("resources.quotes.randomEyebrow", language))}</p><div data-quote-random aria-live="polite"><p class="resourcesQuotes__randomQuote">${esc(featured.quote)}</p><p class="resourcesQuotes__reflection">${esc(featured.reflection)}</p><p class="resourcesQuotes__source">${esc(featured.source)} · ${esc(featured.part)}</p></div></div><div class="resourcesQuotes__randomActions"><button type="button" class="button" data-quote-random-button data-i18n="resources.quotes.randomButton">${esc(t("resources.quotes.randomButton", language))}</button><button type="button" class="button button--secondary" data-quote-copy data-i18n="resources.quotes.copy">${esc(t("resources.quotes.copy", language))}</button><button type="button" class="button button--secondary" data-quote-share data-i18n="resources.quotes.share">${esc(t("resources.quotes.share", language))}</button><span data-copy-feedback role="status" aria-live="polite"></span></div></div><div class="resourcesQuotes__wall" aria-labelledby="resources-quotes-wall-title"><div class="resourcesQuotes__wallHeader"><div><p class="eyebrow" data-i18n="resources.quotes.wallEyebrow">${esc(t("resources.quotes.wallEyebrow", language))}</p><h3 id="resources-quotes-wall-title" data-i18n="resources.quotes.wallTitle">${esc(t("resources.quotes.wallTitle", language))}</h3></div><div class="resourcesQuotes__filters" role="group" aria-label="${esc(t("resources.quotes.filterLabel", language))}">${filters}</div></div><div class="resourcesQuotes__grid">${cards}</div></div></section>`;
}
